### ISSUE TITLE
pip3 install bblfsh fails on macOS Mojave

### ISSUE THREAD

**Issue by alichtman** [bblfsh/client-python#148] opened 2019-03-25 22:24 UTC
**Environment**

- Python 3.6.4
- MacOS Mojave 10.14.3

```
➜ pip3 install bblfsh                                                                                                                                                     5:19PM 
Collecting bblfsh
  Downloading https://files.pythonhosted.org/packages/8a/e1/f469e519b947b2e1d9fd901910133d60fd0dad53f695aacee1fbc210c0ef/bblfsh-3.0.0.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 92kB/s 
Collecting grpcio>=1.13.0 (from bblfsh)
  Downloading https://files.pythonhosted.org/packages/b1/45/0ae182eb92a516a2485e803236eaa90b99d17fea0b3e32d891ce5d33893a/grpcio-1.19.0-cp36-cp36m-macosx_10_9_x86_64.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 5.7MB/s 
Collecting grpcio-tools>=1.13.0 (from bblfsh)
  Downloading https://files.pythonhosted.org/packages/c9/f6/3086a2fbccd2c8cc0d76f0d2b2337f4b7ba3df8be21ea3570a0ff73115f0/grpcio_tools-1.19.0-cp36-cp36m-macosx_10_9_x86_64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 4.0MB/s 
Collecting docker (from bblfsh)
  Downloading https://files.pythonhosted.org/packages/fb/d8/8242b8fb3bd3000274fbf5ac1a06cdba8a5ccbcf4e2a8c05f0ab37999fd8/docker-3.7.1-py2.py3-none-any.whl (134kB)
    100% |████████████████████████████████| 143kB 11.1MB/s 
Requirement already satisfied: protobuf>=3.4.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from bblfsh) (3.5.2.post1)
Requirement already satisfied: six>=1.5.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from grpcio>=1.13.0->bblfsh) (1.11.0)
Collecting docker-pycreds>=0.4.0 (from docker->bblfsh)
  Downloading https://files.pythonhosted.org/packages/f5/e8/f6bd1eee09314e7e6dee49cbe2c5e22314ccdb38db16c9fc72d2fa80d054/docker_pycreds-0.4.0-py2.py3-none-any.whl
Requirement already satisfied: websocket-client>=0.32.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from docker->bblfsh) (0.40.0)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from docker->bblfsh) (2.19.1)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from protobuf>=3.4.0->bblfsh) (40.6.3)
Requirement already satisfied: idna<2.8,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests!=2.18.0,>=2.14.2->docker->bblfsh) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests!=2.18.0,>=2.14.2->docker->bblfsh) (2018.8.24)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests!=2.18.0,>=2.14.2->docker->bblfsh) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests!=2.18.0,>=2.14.2->docker->bblfsh) (3.0.4)
Building wheels for collected packages: bblfsh
  Running setup.py bdist_wheel for bblfsh ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ph/ffxb58fj3gv76s5swk23wmzw0000gn/T/pip-install-v8qgvj3l/bblfsh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/ph/ffxb58fj3gv76s5swk23wmzw0000gn/T/pip-wheel-uv78kmkq --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.6
  creating build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/node_iterator.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/compat.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/type_aliases.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/client.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/tree_order.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/result_context.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/test.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/aliases.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/test_compat.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/launcher.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/node.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  copying bblfsh/__main__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg
  copying bblfsh/gopkg/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/github
  copying bblfsh/github/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in
  copying bblfsh/gopkg/in/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh
  copying bblfsh/gopkg/in/bblfsh/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk
  copying bblfsh/gopkg/in/bblfsh/sdk/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1
  copying bblfsh/gopkg/in/bblfsh/sdk/v1/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2
  copying bblfsh/gopkg/in/bblfsh/sdk/v2/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/uast
  copying bblfsh/gopkg/in/bblfsh/sdk/v1/uast/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/uast
  copying bblfsh/gopkg/in/bblfsh/sdk/v1/uast/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/uast
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
  copying bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
  copying bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
  copying bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/generated_pb2_grpc.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/uast
  copying bblfsh/gopkg/in/bblfsh/sdk/v2/uast/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/uast
  copying bblfsh/gopkg/in/bblfsh/sdk/v2/uast/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/uast
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
  copying bblfsh/gopkg/in/bblfsh/sdk/v2/protocol/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
  copying bblfsh/gopkg/in/bblfsh/sdk/v2/protocol/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
  copying bblfsh/gopkg/in/bblfsh/sdk/v2/protocol/generated_pb2_grpc.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com
  copying bblfsh/github/com/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo
  copying bblfsh/github/com/gogo/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf
  copying bblfsh/github/com/gogo/protobuf/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf
  creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf/gogoproto
  copying bblfsh/github/com/gogo/protobuf/gogoproto/gogo_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf/gogoproto
  copying bblfsh/github/com/gogo/protobuf/gogoproto/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf/gogoproto
  running build_ext
  building 'bblfsh.pyuast' extension
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/bblfsh
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ibblfsh/libuast -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c bblfsh/pyuast.cc -o build/temp.macosx-10.6-intel-3.6/bblfsh/pyuast.o -std=c++11
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  bblfsh/pyuast.cc:1:10: fatal error: 'cstdint' file not found
  #include <cstdint>
           ^~~~~~~~~
  1 warning and 1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for bblfsh
  Running setup.py clean for bblfsh
Failed to build bblfsh
Installing collected packages: grpcio, grpcio-tools, docker-pycreds, docker, bblfsh
  Running setup.py install for bblfsh ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ph/ffxb58fj3gv76s5swk23wmzw0000gn/T/pip-install-v8qgvj3l/bblfsh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ph/ffxb58fj3gv76s5swk23wmzw0000gn/T/pip-record-sgjt3yaf/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/node_iterator.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/compat.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/type_aliases.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/client.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/tree_order.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/result_context.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/test.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/aliases.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/test_compat.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/launcher.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/node.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    copying bblfsh/__main__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg
    copying bblfsh/gopkg/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/github
    copying bblfsh/github/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in
    copying bblfsh/gopkg/in/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh
    copying bblfsh/gopkg/in/bblfsh/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk
    copying bblfsh/gopkg/in/bblfsh/sdk/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1
    copying bblfsh/gopkg/in/bblfsh/sdk/v1/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2
    copying bblfsh/gopkg/in/bblfsh/sdk/v2/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/uast
    copying bblfsh/gopkg/in/bblfsh/sdk/v1/uast/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/uast
    copying bblfsh/gopkg/in/bblfsh/sdk/v1/uast/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/uast
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
    copying bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
    copying bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
    copying bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/generated_pb2_grpc.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v1/protocol
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/uast
    copying bblfsh/gopkg/in/bblfsh/sdk/v2/uast/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/uast
    copying bblfsh/gopkg/in/bblfsh/sdk/v2/uast/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/uast
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
    copying bblfsh/gopkg/in/bblfsh/sdk/v2/protocol/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
    copying bblfsh/gopkg/in/bblfsh/sdk/v2/protocol/generated_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
    copying bblfsh/gopkg/in/bblfsh/sdk/v2/protocol/generated_pb2_grpc.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/gopkg/in/bblfsh/sdk/v2/protocol
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com
    copying bblfsh/github/com/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo
    copying bblfsh/github/com/gogo/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf
    copying bblfsh/github/com/gogo/protobuf/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf
    creating build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf/gogoproto
    copying bblfsh/github/com/gogo/protobuf/gogoproto/gogo_pb2.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf/gogoproto
    copying bblfsh/github/com/gogo/protobuf/gogoproto/__init__.py -> build/lib.macosx-10.6-intel-3.6/bblfsh/github/com/gogo/protobuf/gogoproto
    running build_ext
    building 'bblfsh.pyuast' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/bblfsh
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ibblfsh/libuast -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c bblfsh/pyuast.cc -o build/temp.macosx-10.6-intel-3.6/bblfsh/pyuast.o -std=c++11
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    bblfsh/pyuast.cc:1:10: fatal error: 'cstdint' file not found
    #include <cstdint>
             ^~~~~~~~~
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ph/ffxb58fj3gv76s5swk23wmzw0000gn/T/pip-install-v8qgvj3l/bblfsh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ph/ffxb58fj3gv76s5swk23wmzw0000gn/T/pip-record-sgjt3yaf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ph/ffxb58fj3gv76s5swk23wmzw0000gn/T/pip-install-v8qgvj3l/bblfsh/
```

This may be a compiler version issue on my end, but I figured it was worth reporting until I had time to dig into it further.

**Comment by creachadair** [comment] 2019-03-25 23:33
I haven't yet attempted to reproduce this, but it looks as if you may not having a complete C++ compiler installation. Since you are on macOS, you may need to install XCode.

What do you get if you run this?

```shell
$ xcodebuild -version
```

If it cannot find `xcodebuild`, or if you get an error like `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`, you may need to run either

```shell
$ softwareupdate --install Xcode  # to install XCode
```

or

```shell
$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

to activate the installed version. If none of that helps, please let us know, and we can dig further.

**Comment by alichtman** [comment] 2019-03-26 03:53
```
➜ xcodebuild -version
Xcode 10.1
Build version 10B61
```

I do have the XCode toolchain installed.

**Comment by creachadair** [comment] 2019-03-28 21:53
Thanks for checking. I have a couple theories about what may be going on here, which I'll have to investigate in more detail.

**Comment by creachadair** [comment] 2019-04-02 18:05
I suspected we might not be setting `-std=` correctly in our setup scripts, but I'm having trouble reproducing the original issue.

Here's my setup, from as clean an install as I was able to manage:

```
$ brew install python3
$ python3 -V
Python 3.7.3

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

$ pip3 list
Package    Version
---------- -------
pip        19.0.3 
setuptools 40.8.0 
wheel      0.33.1 
```

But in this setup, `pip3 install bblfsh` does not produce any errors.

Obviously it did for you, but I'm having difficulty isolating what's different between our systems, other than that I got the latest Mojave update (which I think is unlikely to cause any issues).

**Comment by alichtman** [comment] 2019-04-03 01:21
I no longer need to use `bblfsh`, so in a way I've solved my problem. It might be a me-specific thing, in which case this isn't a huge deal. If you're not able to reproduce it, I wouldn't worry about it for now.

**Comment by creachadair** [comment] 2019-04-03 14:39
I'm curious to know: Did you wind up using a different client, or something else entirely?

**Comment by dennwc** [comment] 2019-06-14 17:34
@creachadair Does https://github.com/bblfsh/client-python/pull/157 fix this?

**Comment by creachadair** [comment] 2019-06-14 18:02
> @creachadair Does #157 fix this?

Yes, I believe so—I was able to `pip install bblfsh; python3 -c "import bblfsh"` without error at 3.0.4.

**Comment by dennwc** [comment] 2019-06-14 18:32
OK, closing.

**Closed by dennwc** 2019-06-14 18:32 UTC
Labels: question
