### ISSUE TITLE
Installation problems v0.1.0

### ISSUE THREAD

**Issue by zurk** [bblfsh/client-python#24] opened 2017-09-07 17:33 UTC
When I try to follow installation notes in [README](https://github.com/bblfsh/client-python/blob/master/README.md) I failed.

`pip3 install bblfsh` leads to the error:
```
pip3 install bblfsh
Collecting bblfsh
  Downloading bblfsh-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    make: *** No rule to make target 'deps'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m2t1aa3i/bblfsh/setup.py", line 16, in <module>
        subprocess.check_output(['make', 'deps'])
      File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', 'deps']' returned non-zero exit status 2

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m2t1aa3i/bblfsh/
```

and 
```
git clone https://github.com/bblfsh/client-python.git
cd client-python
make install
```
leads to the next error:
```
Cloning into 'client-python'...
remote: Counting objects: 280, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 280 (delta 11), reused 21 (delta 8), pack-reused 255
Receiving objects: 100% (280/280), 131.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (132/132), done.
make: *** No rule to make target `install'.  Stop.
```

I was able to install it using
```
git clone https://github.com/bblfsh/client-python.git
cd client-python
pip3 install .
```

**Comment by juanjux** [comment] 2017-09-08 07:29
I can reproduce it with the system's pip, but curiously it works with pyenv. I'll take a look.

**Comment by juanjux** [comment] 2017-09-08 08:12
Looks like the version packaged in pypy removes some files (DCO, LICENSE, MAINTAINERS, requirements.txt and Makefile, the last one is the one that produces the failure). But the release `.tar.gz` on github is fine.

I'll investigate the cause of this difference.

**Comment by juanjux** [comment] 2017-09-08 10:06
Fixed by #26.

**Comment by zurk** [comment] 2017-09-08 10:16
Yes, It works for Python 3, thank you! 
I think you can close it.
But I find another problem for Python 2 https://github.com/bblfsh/client-python/issues/27.

**Comment by zurk** [comment] 2017-09-08 10:32
Oh, It works on mac, but still some problems on Ubuntu.
https://gist.github.com/zurk/323f1bb73e4bbf5c981bf17d08e187c9

**Comment by juanjux** [comment] 2017-09-08 10:36
The header files for libxml2 (libxml2-dev in Ubuntu) need to be installed, I'll update the README.

**Closed** 2017-09-09 17:16 UTC
